# Deploy when CI succeeds on a push to main
name: CD

on:
  workflow_run:
    branches: [main]
    workflows: ['CI']
    type: [completed]

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

env:
  INFURA_ID: ${{ secrets.INFURA_ID }}
  INFURA_SECRET: ${{ secrets.INFURA_SECRET }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  API_URL: ${{ secrets.API_URL }}
  SUBGRAPH_GQL_URL: ${{ secrets.SUBGRAPH_GQL_URL }}
  CHAIN: testnet
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš§ Checkout
        uses: actions/checkout@v2

      - name: ğŸš€ Heroku - Build, Push and Release
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          process_type: web
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          # docker_options: ""

  subgraph:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: ğŸš§ Checkout
        uses: actions/checkout@v2

      - name: ğŸš§ Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: ğŸ“¦ Install
        run: yarn install

      - name: ğŸš§ Configure
        run: yarn subgraph configure:testnet

      - name: ğŸš§ Auth
        run: yarn subgraph auth ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

      - name: ğŸ—ï¸ Generate
        run: yarn subgraph generate

      - name: ğŸ—ï¸ Build
        run: yarn subgraph build

      - name: ğŸš€ Deploy
        run: yarn subgraph deploy:metasafe

  app:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: ğŸš§ Checkout
        uses: actions/checkout@v2

      - name: ğŸš§ Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: ğŸš§ Setup Expo
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest

      - name: ğŸ“¦ Install
        run: yarn install

      - name: ğŸ—ï¸ Build Libs
        run: yarn build:libs

      - name: ğŸš€ Publish
        run: yarn app publish
