name: Deployment - Production

on:
  workflow_run:
    branches: [main]
    workflows: ['Integration']
    type: [completed]

concurrency:
  group: deployment-${{ github.ref }}
  cancel-in-progress: true

env:
  SUBGRAPH_GQL_URL: ${{ secrets.SUBGRAPH_GQL_URL_PROD }}

jobs:
  api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: main - api
    steps:
      - name: ğŸš€ Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_DEPLOY_HOOK }}
          method: POST

  app:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    environment: app-prod
    env:
      # Environment
      API_URL: ${{ secrets.API_URL }}
      # Repository
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - name: ğŸš§ Checkout
        uses: actions/checkout@v2

      - name: ğŸš§ Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: ğŸš§ Setup Expo
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: ğŸ“¦ Install
        run: yarn install

      - name: ğŸ—ï¸ Prebuild
        run: yarn app prebuild

      - name: ğŸš€ Publish update
        run: yarn app eas update --auto --non-interactive

      # - name: ğŸ—ï¸ Build
      #   run: yarn eas build -p android --profile production

      # - name: ğŸš€ Publish
      #   run: yarn eas submit -p android --profile production --latest

  # subgraph:
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   runs-on: ubuntu-latest
  #   environment: subgraph-prod
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #     - name: ğŸš§ Checkout
  #       uses: actions/checkout@v2

  #     - name: ğŸš§ Use Node ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'yarn'

  #     - name: ğŸ“¦ Install
  #       run: yarn install

  #     - name: ğŸš§ Configure
  #       run: yarn subgraph configure:testnet

  #     # - name: ğŸš§ Auth
  #     #   run: yarn subgraph auth ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

  #     - name: ğŸ—ï¸ Generate
  #       run: yarn subgraph generate

  #     - name: ğŸ—ï¸ Build
  #       run: yarn subgraph build

  #     - name: ğŸš€ Deploy
  #       run: yarn subgraph prod:deploy
