name: Deployment - Development

on:
  push:
    branches: [dev]
  # workflow_run:
  #   branches: [dev]
  #   workflows: ['Tests']
  #   type: [completed]

concurrency:
  group: deployment-${{ github.ref }}
  cancel-in-progress: true

env:
  SUBGRAPH_GQL_URL: 'http://graph.allopay.io/subgraphs/name/allopay-dev'

jobs:
  api:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: 'main - api-dev'
    steps:
      - name: ğŸš€ Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_DEPLOY_HOOK }}
          method: POST

  app:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    environment: 'app-dev'
    env:
      # Environment
      API_URL: 'https://api-dev.allopay.io'
      # Repository
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - name: ğŸš§ Checkout
        uses: actions/checkout@v3

      - name: ğŸš§ Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: ğŸš§ Setup Expo
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: ğŸ“¦ Install
        run: yarn install

      - name: ğŸ—ï¸ Prebuild
        run: yarn app prebuild

      - name: ğŸš€ Publish update
        run: yarn app eas update --auto --non-interactive

      # - name: ğŸ—ï¸ Build
      #   run: yarn eas build -p android --profile development

      # - name: ğŸš€ Publish
      #   run: yarn eas submit -p android --profile development --latest

  subgraph:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: ğŸš§ Checkout
        uses: actions/checkout@v3

      - name: ğŸš§ Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: ğŸ“¦ Install
        run: yarn install

      - name: ğŸš§ Configure
        run: yarn subgraph configure:testnet

      - name: ğŸš§ Auth
        run: yarn subgraph hosted:auth ${{ secrets.THEGRAPH_ACCESS_TOKEN }}

      - name: ğŸ—ï¸ Generate
        run: yarn subgraph generate

      - name: ğŸ—ï¸ Build
        run: yarn subgraph build

      - name: ğŸš€ Deploy
        run: yarn subgraph dev:deploy-hosted
